version: '3.9'

services:
  cassandra:
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=earthpoints
  redis:
    image: redis:6.2.6
    ports:
      - ${REDIS_PORT}:6379
  dev:
      container_name: nestjs_api_dev
      image: nestjs-api-dev:1.0.0
      build:
          context: .
          target: development
          dockerfile: ./Dockerfile
      command: npm run start:debug
      ports:
          - ${WEB_APP_PORT}:3000
          - 9229:9229
      volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
      restart: unless-stopped
      environment:
        - DEBUG=*
        - NODE_ENV=development
      env_file:
        - .env      
      depends_on:
        - cassandra
        - redis
  prod:
      container_name: nestjs_api_prod
      image: nestjs-api-prod:1.0.0
      build:
          context: .
          target: production
          dockerfile: ./Dockerfile
      command: npm run start:prod
      ports:
          - ${WEB_APP_PORT}:3000
          - 9229:9229
      volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
          - /usr/src/app/dist
      restart: unless-stopped
      env_file:
        - .env      
      depends_on:
        - cassandra
        - redis
