apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra-claim0
  name: cassandra-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
  - port: 9042
  selector:
    app: cassandra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values:
                - earthpoints-db
      terminationGracePeriodSeconds: 120
      containers:
        - name: cassandra
          image: cassandra:4.0
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: earthpoints    
            - name: KUBE_CONFIG_APPLY_DATE
              value: '202203110428'
          ports:
            - containerPort: 9042
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: cassandra-volume
      volumes:
        - name: cassandra-volume
          persistentVolumeClaim:
            claimName: cassandra-claim0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: redis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values:
                - earthpoints-poc
      terminationGracePeriodSeconds: 120
      containers:
        - name: redis
          image: redis:6.2.6
          ports:
            - containerPort: 6379
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: earthpoints-poc
  labels:
    app: earthpoints-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earthpoints-poc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: earthpoints-poc
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values:
                - earthpoints-poc
      terminationGracePeriodSeconds: 120
      containers:
        - name: earthpoints-poc
          image: registry.digitalocean.com/earthpoints/earthpoints-poc:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          env:
          - name: KUBE_CONFIG_APPLY_DATE
            value: '<DATE>'              
          envFrom:
          - secretRef:
              name: earthpoints-poc-secret
          startupProbe:
            tcpSocket:
              port: 3000
            failureThreshold: 30
            periodSeconds: 10