apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: earthpoints-que
  namespace: uat
  labels:
    app: earthpoints-que
spec:
  serviceName: earthpoints-que
  replicas: 1
  selector:
    matchLabels:
      app: earthpoints-que
  strategy:
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: earthpoints-que
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values:
                - earthpoints-poc
      terminationGracePeriodSeconds: 120
      containers:
        - name: earthpoints-que
          image: registry.digitalocean.com/earthpoints/earthpoints-poc:latest-uat
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          env:
          - name: KUBE_CONFIG_APPLY_DATE
            value: '<DATE>'              
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          envFrom:
          - secretRef:
              name: earthpoints-poc-secret
          startupProbe:
            tcpSocket:
              port: 3000
            failureThreshold: 30
            periodSeconds: 10