apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra-claim0
  name: cassandra-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
  - port: 9042
  selector:
    app: cassandra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
        - name: cassandra
          image: cassandra:4.0
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: earthpoints          
          ports:
            - containerPort: 9042
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: cassandra-volume
      volumes:
        - name: cassandra-volume
          persistentVolumeClaim:
            claimName: cassandra-claim0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: earthpoints-poc
  labels:
    app: earthpoints-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: earthpoints-poc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: earthpoints-poc
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: earthpoints-poc
          image: registry.digitalocean.com/earthpoints/earthpoints-poc:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          env:
          - name: KUBE_CONFIG_APPLY_DATE
            value: '<DATE>'              
          envFrom:
          - secretRef:
              name: earthpoints-poc-secret
---
apiVersion: v1
kind: Service
metadata:
  name: earthpoints-poc-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "earthpoints-poc-service"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "20f424dd-149c-494a-92f6-f71683af0b47"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
  selector:
    app: earthpoints-poc