apiVersion: v1
kind: Service
metadata:
  name: earthpoints-poc-service
  namespace: uat
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "earthpoints-poc-service-uat"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "d46e3532-d136-4543-917e-661cf6d7e1b1"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
  selector:
    app: earthpoints-poc