apiVersion: batch/v1
kind: CronJob
metadata:
  name: earthpoints-cron
  namespace: uat
  labels:
    app: earthpoints-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: earthpoints-cron
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                    - earthpoints-poc
          terminationGracePeriodSeconds: 120
          containers:
            - name: earthpoints-cron
              image: registry.digitalocean.com/earthpoints/earthpoints-poc:latest-uat
              imagePullPolicy: "Always"
              command: ["node"]
              args: ["dist/cron", "cron"]
              resources:
                requests:
                  cpu: 100m
                limits:
                  cpu: 100m
              env:
              - name: KUBE_CONFIG_APPLY_DATE
                value: '<DATE>'              
              envFrom:
              - secretRef:
                  name: earthpoints-poc-secret
